name: Deploy Frontend Angular

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'GreenCharger/package-lock.json'

    - name: Install dependencies
      run: |
        cd GreenCharger
        npm ci

    - name: Build Angular app
      run: |
        cd GreenCharger
        npm run build -- --configuration production

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./GreenCharger"
        output_location: "dist/green-charger"
