name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'GreenCharger/**'
      - '.github/workflows/frontend-deploy.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'GreenCharger/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'GreenCharger/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd GreenCharger
          npm install
      
      - name: Build
        run: |
          cd GreenCharger
          npm run build
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # Thay "/" bằng đường dẫn tới thư mục Angular
          app_location: "GreenCharger"                     
          # Nếu bạn không dùng Azure Functions làm API, để trống hoặc xóa luôn
          api_location: ""                              
          # Thư mục build ra, tương đối với app_location
          output_location: "dist/green-charger"           

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
